version: 2.1
executors:
  base-executor:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
  megalinter-executor:
    docker:
      - image: oxsecurity/megalinter-python:v8.3.0
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/RelativeSure/autocopr/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    environment:
      APPLY_FIXES: all
      APPLY_FIXES_EVENT: push
      APPLY_FIXES_MODE: pull_request
      #GITHUB_TOKEN: ${{ secrets.KUBEARCHITECTBOT_TOKEN || secrets.GITHUB_TOKEN }}
      SARIF_REPORTER: true
      GITHUB_STATUS_REPORTER: true
      GITHUB_COMMENT_REPORTER: false
      VALIDATE_ALL_CODEBASE: true
jobs:
  base:
    executor: base-executor
    steps:
      - checkout
  megalinter:
    executor: megalinter-executor
    steps:
      - run: /entrypoint.sh
workflows:
  my-custom-workflow:
    jobs:
      - base
      - megalinter