---
version: 2.1

# define the parameters from the setup config.  
parameters:  
  megalinter:  
    type: boolean  
    default: false  

jobs:
  megalinter:
    docker:
      - image: oxsecurity/megalinter-python:v8.3.0
        auth: 
           username: $DOCKER_HUB_USER
           password: $DOCKER_HUB_PASSWORD
    resource_class: large
    steps: 
      - checkout  
      - run:
          name: ml
          command: |
            export GITHUB_TOKEN=$GH_PACKAGES_TOKEN
            export CI_ACTION_RUN_URL=$CIRCLE_BUILD_URL
            export GITHUB_REPOSITORY=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
            export GITHUB_REF=$CI_PULL_REQUEST
            export GITHUB_SHA=$CIRCLE_SHA1
            export DEFAULT_WORKSPACE=$CIRCLE_WORKING_DIRECTORY
            export GITHUB_WORKSPACE=$CIRCLE_WORKING_DIRECTORY
            export GITHUB_RUN_ID=$CIRCLE_BUILD_NUM
            /bin/bash -ex /entrypoint.sh
      - store_artifacts:
          path: megalinter-reports

workflows:
  megalinter-workflow:
    jobs:
      - megalinter
