name: GH Actions - Update spec files
on:
  # Allows for manually running an update from the actions tab
  workflow_dispatch:

  schedule:
    # Runs every day at ~12am UTC
    - cron: "0 0 * * *"

# Revoke all default permissions
permissions: {}

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    permissions:
      # needed to write updated specs to this repo
      contents: write

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: aidandenlinger/autocopr@3bf4fde911140dffbb665b0ff1ae41702a0a20bc # v1
        with:
          mode: "push"
