name: GH Actions - Update spec files
on:
  # Allows for manually running an update from the actions tab
  workflow_dispatch:

  schedule:
    # Runs every day at ~12am UTC
    - cron: "0 0 * * *"

# Revoke all default permissions
permissions: {}

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    permissions:
      # needed to write updated specs to this repo
      contents: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: aidandenlinger/autocopr@612099e079443983d61b82290a885975a03a5b32 # v1
        with:
          mode: "push"
