name: dagger
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up BuildKit
        uses: docker/setup-buildx-action@v3

      - name: Call Dagger Function to build and publish to ghcr.io
        uses: dagger/dagger-for-github@v7
        with:
          version: "latest"
          verb: call
          module: github.com/daggerverse/dagger-ghcr-demo@v0.1.5
          args: build-and-push --registry=$DOCKER_REGISTRY --image-name=$DOCKER_IMAGE_NAME --username=$DOCKER_USERNAME --password=env:DOCKER_PASSWORD --build-context=github.com/daggerverse/dagger-ghcr-demo
          # assumes the Dagger Cloud token is in
          # a repository secret named DAGGER_CLOUD_TOKEN
          # set via the GitHub UI/CLI
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          DOCKER_REGISTRY: ghcr.io
          DOCKER_IMAGE_NAME: ${{ github.repository }}
          DOCKER_USERNAME: ${{ github.actor }}
          # assumes the container registry password is in
          # a repository secret named REGISTRY_PASSWORD
          # set via the GitHub UI/CL
          #DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}