name: "Release Dev Container Templates & Generate Documentation"
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      - name: Dev Container Build and Run Action
        # You may pin to the exact commit or the version.
        # uses: devcontainers/ci@72700878095f87b851a6c4405a16056caffdc577
        uses: devcontainers/ci@v0.3.1900000328
        with:
          imageName: fedora-python
          push: always
          checkoutPath: .
          subFolder: .devcontainer
          eventFilterForPush: push
          skipContainerUserIdUpdate: false
          noCache: false
