name: "Release Dev Container Templates & Generate Documentation"

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dev Container Build and Run Action
        uses: devcontainers/ci@a56d055efecd725e8cfe370543b6071b79989cc8 # v0.3.1900000349
        with:
          imageName: fedora-python
          push: always
          checkoutPath: .devcontainer
          subFolder: .
          eventFilterForPush: push
          skipContainerUserIdUpdate: false
          noCache: false

      # - name: Push to GitHub Packages
      #   run: |
      #     docker tag fedora-python:latest ghcr.io/${{ github.repository }}/fedora-python:latest
      #     docker push ghcr.io/${{ github.repository }}/fedora-python:latest
