###
# This GitHub Actions runs when there is a push to master/main branch and a new change in the `specs/` folder.
# It will send a webhook to COPR when the WEBHOOK URL actions secret has been set in Settings.
# The WEBHOOK_URL is found under the `Custom webhook(s)` sections on https://copr.fedorainfracloud.org/coprs/<username>/<repo>/integrations/
###
name: File Change Webhook

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "specs/*"
      - ".github/workflows/*"
  workflow_run:
    workflows: [Update spec files]
    types:
      - completed

permissions:
  # Needs to write to this repo
  contents: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          ref: master

      - name: Get changes and send webhook to COPR
        shell: bash
        env:
          WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        run: ./scripts/copr_webhook.sh $WEBHOOK ${{ github.sha }}

  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown

      - name: Update README.md file
        run: python scripts/python_create_readme.py

      - name: Commit and push changes
        shell: bash
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff-index --quiet HEAD; then
            echo "**No changes to README.md with python script to commit**"
          else
            git add README.md
            git commit -m "Update README.md with the list of spec files"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Finalize
        if: failure()
        run: echo "Workflow completed. No changes were necessary."
