name: File Change Webhook

on:
  push:
    branches:
      - "master"
    paths:
      - "specs/*"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Changed Files
        id: changes
        shell: bash
        run: |
          #files_changed=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | cut -c 7- | cut -c -5)
          echo "Files changed: $files_changed"
          echo "CHANGED_FILES=$files_changed" >> "$GITHUB_OUTPUT"

      - name: Send Webhook
        shell: bash
        env:
          CHANGED_FILES: ${{ steps.changes.outputs.CHANGED_FILES }}
          WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        run: |
          echo "Processing webhooks for..."
          echo $CHANGED_FILES
          for file in $CHANGED_FILES; do
            echo "Processing file: $file"
            curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST "$WEBHOOK/$file"
          done
