name: Update spec files
on:
  workflow_dispatch:

  schedule:
    # Runs at 12:00am UTC -> 5:00pm PDT
    - cron: "0 0 * * *"

permissions:
  # Needs to write to this repo
  contents: write

jobs:
  update:
    name: update
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.14" # Need python version for cache
          cache: "pip" # caching pip dependencies

      - name: Cache GraphQL API IDs
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: specs/graphql_id_cache.json
          # This key is overkill - we realy only need to update the
          # cache when a *new* spec file is added, not when *any* spec
          # file changes. However, this seems to be the easiest way
          # to achieve that from within Actions.
          key: graphql-ids-${{ hashFiles('specs/*.spec') }}
          # Make sure even if the specs change it grabs the old cache
          # to start from! Entries are never invalidated, only added
          restore-keys: graphql-ids

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set git user to github-actions[bot]
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Check and update spec files
        run: python -m autocopr.autocopr --verbose --in-place --push specs
        env:
          GITHUB_TOKEN: ${{ secrets.KUBEARCHITECTBOT_TOKEN || secrets.GITHUB_TOKEN }}
